# CatMSG is a simple plugin that allows players to send messages to each other.

# The messages that will be sent to the player
message:
  playernotfound: "&cPlayer not found!"
  senderistarget: "&cYou can't send a message to yourself!"
  usage: "&cUsage: /msg <player> <message>"
  nopermission: "&cYou don't have permission to do that!"
  nomessage: "&cYou must enter a message!"
  reload: "&aPlugin reloaded!"

# {player} is the player who sent the message
# {target} is the player who received the message
# {message} is the message that was sent

msg:
  sender: "&dYou &7-> &d{target} &8» &7{message}"
  target: "&d{player} &7-> &dYou &8» &7{message}"