name: NaMSG
version: '1.0-SNAPSHOT'
main: dev.alesixdev.naMSG.NaMSG
api-version: '1.20'
authors: [ AlesixDev ]

commands:
    namsg:
        description: Send a message to a player
        aliases: [msg, message]
