name: NaMSG
version: '1.0-SNAPSHOT'
main: dev.alesixdev.CatMSG.CatMSG
api-version: '1.20'
authors: [ AlesixDev ]

commands:
    namsg:
        description: Send a message to a player
    msg:
        description: Send a message to a player
        aliases: [message]